language: node_js
node_js:
    - "8.12.0"
script:
    - npm test
    - webpack -p
deploy:
    - provider: s3
      access_key_id: ${AWS_KEY}
      secret_access_key: ${AWS_SECRET_KEY}
      bucket: "research-staging.sagebridge.org"
      skip_cleanup: true
      acl: public_read
      detect_encoding: false
      endpoint: https://research-staging.sagebridge.org.s3-website-us-west-2.amazonaws.com
      region: "us-west-2"
      local_dir: app
      on:
          branch: develop
    - provider: s3
      access_key_id: ${AWS_KEY}
      secret_access_key: ${AWS_SECRET_KEY}
      bucket: "research.sagebridge.org"
      skip_cleanup: true
      acl: public_read
      detect_encoding: false
      endpoint: https://research.sagebridge.org.s3-website-us-west-2.amazonaws.com
      region: "us-west-2"
      local_dir: app
      on:
          branch: release
