language: node_js
node_js:
    0.12.3
script:
    mocha --recursive
    webpack -p
deploy:
    - provider: s3
      access_key_id: ${AWS_KEY}
      secret_access_key: ${AWS_SECRET_KEY}
      bucket: "research-staging.sagebridge.org"
      skip_cleanup: true
      acl: public_read
      detect_encoding: true
      endpoint: research-staging.sagebridge.org.s3-website-us-west-2.amazonaws.com
      region: "us-west-2"
      local_dir: app
      on:
          branch: develop
    - provider: s3
      access_key_id: ${AWS_KEY}
      secret_access_key: ${AWS_SECRET_KEY}
      bucket: "research.sagebridge.org"
      skip_cleanup: true
      acl: public_read
      detect_encoding: true
      endpoint: research.sagebridge.org.s3-website-us-west-2.amazonaws.com
      region: "us-west-2"
      local_dir: app
      on:
          branch: release
