# Change to update
sudo: false
language: python
python: 3.5
cache: pip
fast_finish: true
branches:
  only:
  - develop
  - release
install:
- wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
- unzip -j -n /tmp/infra-utils.zip -x infra-utils-master/.gitignore infra-utils-master/LICENSE infra-utils-master/README.md
- ./setup_aws_cli.sh || travis_terminate 1
script:
- npm install test
- webpack -p
- echo $AwsBucket_$TRAVIS_BRANCH
- aws s3 cp app/ s3://$AwsBucket_$TRAVIS_BRANCH/ --recursive --acl public-read
